package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF7E5260)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF9EBED)
val md_theme_light_onPrimaryContainer = Color(0xFF7E5260)
val md_theme_light_secondary = Color(0xFF9D6B7B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8DEF8)
val md_theme_light_onSecondaryContainer = Color(0xFF211A1D)
val md_theme_light_tertiary = Color(0xFFE8DEF8)
val md_theme_light_onTertiary = Color(0xFF211A1D)
val md_theme_light_tertiaryContainer = Color(0xFFF3E7E9)
val md_theme_light_onTertiaryContainer = Color(0xFF7E5260)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCF7F7)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFF3E7E9)
val md_theme_light_onSurfaceVariant = Color(0xFF4A454E)
val md_theme_light_outline = Color(0xFFF3E7E9)
val md_theme_light_inverseOnSurface = Color(0xFFFCF7F7)
val md_theme_light_inverseSurface = Color(0xFF1D1B1E)
val md_theme_light_inversePrimary = Color(0xFF9D6B7B)
val md_theme_light_surfaceTint = Color(0xFF7E5260)
